# Generated by Django 3.1.3 on 2021-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210601_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='toppings',
            field=models.ManyToManyField(to='product.ProductPhoto'),
        ),
    ]
