# Generated by Django 3.1.3 on 2021-06-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210606_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productphoto',
            old_name='photo',
            new_name='url',
        ),
    ]
